### ISSUE TITLE
How to modify the argument to translate the English to other language?

### ISSUE THREAD

**Issue by snowmint** [fortypercnt/stream-translator#12]
Is there a possible argument for setting the translated language instead of English?
I was looking into the code but I am not sure where I can modify it to match my thought.
Thank you for reading my question, hope there is a way to do this.

**Comment by fortypercnt** [comment]
This project uses OpenAI's Whisper model, which is only trained on any-to-english translation and on transcription (output in the same language as audio input) tasks. Any-to-any translation is not possible with this model.
Something you could do to get output in other languages would be to run the output through some translation API. [This fork](https://github.com/ionic-bond/stream-translator-gpt) implements something like that (I haven't tested it).
