### ISSUE TITLE
Unable to open URL ：SSLError

### ISSUE THREAD

**Issue by Simon986793021** [fortypercnt/stream-translator#8]
when i run “python3 translator.py https://www.youtube.com/watch\?v\=eRVUD4-nZOw”，
I got an error:ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure
I attempt to ignore the ssl verify ,but cannot work.

info:
python:3.9.5

**Comment by fortypercnt** [comment]
I can't reproduce this. Given that it is an ssl error, it probably comes from somewhere in streamlink. You can check by running the following command and seeing if it also throws an error:
```
streamlink https://www.youtube.com/watch\?v\=eRVUD4-nZOw best
```

**Comment by Simon986793021** [comment]
I fixed with add proxy command in terminal
