### ISSUE TITLE
RT audio from microphone

### ISSUE THREAD

**Issue by elia-ashraf** [fortypercnt/stream-translator#9]
Hi,

I know it clears says in the begining of the read.me file that stream-translator transcribes/translates live audio streams from URLs.

But I still wanted to know:
Can it be used to translate/transrcibe real-time audio from the microphone of the system or PC?

**Comment by fortypercnt** [comment]
Capturing system audio/mic is the simplest way to make a whisper live translation demo, so you can find plenty of projects in the [whisper show and tell](https://github.com/openai/whisper/discussions/categories/show-and-tell) which are built specifically for that (e.g., https://github.com/Awexander/audioWhisper, https://github.com/davabase/whisper_real_time).
If you want to have the functionality with this repo, someone made a hacky solution [here](https://github.com/fortypercnt/stream-translator/issues/7#issuecomment-1498010902) by capturing system audio/mic with OBS and streaming it to a local rtmp server.
